### ISSUE TITLE
Error in setting up the module XGBRegressorTraining using the example provided

### ISSUE THREAD

**Issue by setuc** [Azure/AzureMachineLearningGallery#46]
Hi,
 I was trying to create an example module, but i noticed that the example provided from the  [repository](https://github.com/Azure/AzureMachineLearningGallery/tree/main/components/automobile-price-prediction/xgboost-regressor-training), runs into an issue while loading the modules from the  following lline 

``` python
from azureml.studio.core.io.data_frame_directory import load_data_frame_from_directory, save_data_frame_to_directory

```
I get the following error:
```
Traceback (most recent call last):
  File "XGBRegressorTraining.py", line 9, in <module>
    from azureml.studio.core.io.data_frame_directory import load_data_frame_from_directory, save_data_frame_to_directory
  File "/azureml-envs/azureml_b4f25b1a5c5156b092c5604de72bc8de/lib/python3.7/site-packages/azureml/studio/core/io/data_frame_directory.py", line 9, in <module>
    from azureml.studio.core.data_frame_schema import DataFrameSchema
  File "/azureml-envs/azureml_b4f25b1a5c5156b092c5604de72bc8de/lib/python3.7/site-packages/azureml/studio/core/data_frame_schema.py", line 6, in <module>
    from pandas.core.dtypes.common import is_bool_dtype, is_integer_dtype, is_float_dtype, is_string_like_dtype
ImportError: cannot import name 'is_string_like_dtype' from 'pandas.core.dtypes.common' (/azureml-envs/azureml_b4f25b1a5c5156b092c5604de72bc8de/lib/python3.7/site-packages/pandas/core/dtypes/common.py)
```

**Comment by christianzeller** [comment]
I'm experiencing the same issue. I am using this code in some custom modules. Last successful run was 30.08.2021.

**Comment by saurius** [comment]
I'm getting the exact same error, does anyone have a solution? I'm guessing it has to do with versions of Pandas or AzureML stated in the YAML

**Comment by saurius** [comment]
I managed to run it by changing the pandas vesion in the YAML to 1.2.0 just do that and it will run. You also need to change the version. 

`
        - pandas==1.2.0
`

**Comment by manu-kanwarpal** [comment]
I'm also facing an issue with the custom component, and changing the pandas version did not help. Here's the error I'm getting:

User program failed with ImportError: cannot import name 'is_string_like_dtype' from 'pandas.core.dtypes.common' (/azureml-envs/azureml_b4f25b1a5c5156b092c5604de72bc8de/lib/python3.7/site-packages/pandas/core/dtypes/common.py)
